baseURL = 'hyyps://moranis.netfily.app'
languageCode = 'zh-cn'
title = 'Moranis-Blog'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]

# 默认语言设置
defaultContentLanguage = 'zh'
hasCJKLanguage = true

# 作者信息
[params]
  author = "Moranis"
  description = "我爱你 像脉搏 像隐晦 像呼吸"
  # 使用绝对URL路径
  featured_image = "/images/labixiaoxin.png"
  # 网站图标
  favicon = "/images/bochi-git.jpg"
  # 显示阅读时间
  show_reading_time = true
  # 显示相关文章
  show_related = true
  # 显示社交分享按钮
  show_social_sharing_buttons = true

# 菜单配置
[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 3

# 社交媒体链接
[params.social]
  github = "ParadoxMoranis"
  # 可以添加更多社交媒体链接

# 分页设置
paginate = 6

# 代码高亮设置
[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = true

# 启用 emoji 支持
enableEmoji = true

# 启用目录
[markup.tableOfContents]
  endLevel = 1
  ordered = false
  startLevel = 1
